<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerN0xZfB1\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerN0xZfB1/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerN0xZfB1.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerN0xZfB1\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerN0xZfB1\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'N0xZfB1',
    'container.build_id' => '44b908b3',
    'container.build_time' => 1558357157,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerN0xZfB1');
