<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFovf36H\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFovf36H/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerFovf36H.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerFovf36H\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerFovf36H\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'Fovf36H',
    'container.build_id' => '414333c4',
    'container.build_time' => 1558359190,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerFovf36H');
