<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerOsoyVo1\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerOsoyVo1/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerOsoyVo1.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerOsoyVo1\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerOsoyVo1\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'OsoyVo1',
    'container.build_id' => '5ea2aaaa',
    'container.build_time' => 1558236122,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerOsoyVo1');
